[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7"
glam = "0.29"
kiddo = "5.2.2"
memchr = "2.7"
mimalloc = "0.1"
num-complex = "0.4"
prettytable-rs = "0.10"
rayon = "1.10"
serde_json = "1.0"
twox-hash = "2.1.2"
union-find = "0.4.3"


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bin]]
name = "aoc"
path = "src/main.rs"

[[bin]]
name = "profile"
path = "src/bin/profile.rs"

[[bench]]
name = "days"
harness = false

[profile.profiling]
inherits = "release"
debug = true
